### ISSUE TITLE
1.3.3 breaks my build

### ISSUE THREAD

**Issue by ds82** [npm/write-file-atomic#18]
```
(rj-titan)root@oglach-0:/home/buildbot/jenkins/workspace/rea-jet-firmware-etx/origin/build/3.72/psens_fix/titan-web/titan-gui-web# ./node_modules/.bin/typings install

TypeError: Not an integer
    at Object.fs.writeSync (fs.js:528:18)
    at Function.writeFileSync [as sync] (/home/buildbot/jenkins/workspace/rea-jet-firmware-etx/origin/build/3.72/psens_fix/titan-web/titan-gui-web/node_modules/typings/node_modules/typings-core/node_modules/configstore/node_modules/write-
file-atomic/index.js:114:10)
    at Object.create.all.set (/home/buildbot/jenkins/workspace/rea-jet-firmware-etx/origin/build/3.72/psens_fix/titan-web/titan-gui-web/node_modules/typings/node_modules/typings-core/node_modules/configstore/index.js:63:21)
    at Object.Configstore (/home/buildbot/jenkins/workspace/rea-jet-firmware-etx/origin/build/3.72/psens_fix/titan-web/titan-gui-web/node_modules/typings/node_modules/typings-core/node_modules/configstore/index.js:28:11)
    at Object.<anonymous> (/home/buildbot/jenkins/workspace/rea-jet-firmware-etx/origin/build/3.72/psens_fix/titan-web/titan-gui-web/node_modules/typings/node_modules/typings-core/dist/utils/store.js:5:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/buildbot/jenkins/workspace/rea-jet-firmware-etx/origin/build/3.72/psens_fix/titan-web/titan-gui-web/node_modules/typings/node_modules/typings-core/dist/utils/fs.js:29:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

Rolling back manually to write-file-atomic@1.3.1 fixes it.

**Comment by zero2duo** [comment]
Thanks, did what you suggested and now my Ambari builds are passing/building successfully again.

**Comment by SamVerschueren** [comment]
This should be fixed asap. It is breaking builds...

**Comment by rpiskule** [comment]
Bower 1.5.3 is breaking my builds. I had to roll back to Bower 1.5.2.

TypeError: Not an integer
    at Object.fs.writeSync (fs.js:540:18)
    at Function.writeFileSync [as sync] (/usr/lib/node_modules/bower/node_modules/write-file-atomic/index.js:114:10)
    at Object.create.all.set (/usr/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:62:21)
    at Object.Configstore (/usr/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:27:11)
    at new Insight (/usr/lib/node_modules/bower/node_modules/insight/lib/index.js:37:34)
    at ensureInsight (/usr/lib/node_modules/bower/lib/util/analytics.js:25:19)
    at Object.setup (/usr/lib/node_modules/bower/lib/util/analytics.js:41:9)
    at Object.<anonymous> (/usr/lib/node_modules/bower/bin/bower:72:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by zkat** [comment]
I bet this happens when `data` is a `buffer`. Hah. The Node API seems really weird here -- the call is exactly the same, but the parameters change completely whether your data is a buffer or a string. Stand by, I'm gonna make sure that's what's going on.

**Comment by iarna** [comment]
```
    if (Buffer.isBuffer(data)) {
      fs.writeSync(fd, data, 0, data.length)
    } else {
      fs.writeSync(fd, data, options.encoding || 'utf8')
    }
```

**Comment by iarna** [comment]
It would be super helpful if someone who's seeing this can share what version of Node.js they're seeing it with.

**Comment by SamVerschueren** [comment]
0.10.x

**Comment by iarna** [comment]
Aaaah, yeah, that explains a lot, we don't support 0.10 so it's not in our test matrix. (In fact, our tests use Object.assign and can't even run on 0.10!)

**Comment by SamVerschueren** [comment]
It has a fallback https://github.com/npm/write-file-atomic/blob/master/index.js#L9

It always worked on 0.10 so it's definitely something

**Comment by SamVerschueren** [comment]
Oh, you meant the tests...

**Comment by iarna** [comment]
@zkat and I have been talking and we've settled on a going-forward-policy that we'll bump the major when we drop support for a Node.js version (even if we haven't yet broken compatibility with it.)

If you're curious, we follow the Node.js support schedule. When a version drops from long-term support we drop support in our modules. That means at the moment v4, v6 and v7 are supported.

**Comment by iarna** [comment]
1.3.4 is out with a fix and 2.0.0 is out for any future changes.

**Comment by SamVerschueren** [comment]
Thanks for the quick follow up @iarna and @zkat!

**Comment by rpiskule** [comment]
@SamVerschueren 
"It always worked on 0.10 so it's definitely something"

I completely agree. Bower 1.5.3 always worked on Node 0.10, so why is it breaking now? I thought this was released code?

@iarna 
"Object.assign and can't even run on 0.10!)"

This shouldn't matter. The code was released, and the released code worked. The released code should have never changed.

@iarna 
I'm still having difficulty figuring out why downgrading to Bower 1.5.2 resolved my problem. I'm not trying to pin the blame on you (maybe I need talk to the guys at Bower, as well as our developers), but someone, somewhere did something bad practice.

Released code shouldn't ever be re-released. Do you have further insight as to why write-file-atomic 1.3.3 suddenly stopped working?

**Comment by SamVerschueren** [comment]
Version 1.3.4 should work now so I guess that reinstalling Bower would fix the problem.

**Comment by ds82** [comment]
@rpiskule The released code did not change. A transitive dependency of bower did not pin to an exact version of write-file-atomic. When write-file-atomic@1.3.3 was released and and you (re-)installed bower you automatically received the update because the dependencies were not pinned.

Like @iarna said, it was a mistake releasing a patch version of write-file-atomic that dropped node 0.10 support. That should (and is now) have been a major update.

**Comment by rpiskule** [comment]
@ds82 
So did Bower fix this? Magically things are working today.

**Comment by SamVerschueren** [comment]
That's how semver works. It automatically picks up the latest patch (depending on the configuration). So yes, things are working again.
