### ISSUE TITLE
[ERROR] <npm Start no Work>

### ISSUE THREAD

**Issue by MBajaber** [npm/write-file-atomic#72]
![pr6](https://user-images.githubusercontent.com/58700226/97811608-ca4d6100-1c8c-11eb-88a6-ef8d5b757ee6.png)

I download React i got The files but when i want to start it it's not work with me
also i got some error and when i go to npm-catche there some debugs i uninstall many times and try again also same error

########   AppData\Roaming\npm-cache\_logs debges 

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\USER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v13.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle learn-react@0.1.0~prestart: learn-react@0.1.0
6 info lifecycle learn-react@0.1.0~start: learn-react@0.1.0
7 verbose lifecycle learn-react@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle learn-react@0.1.0~start: PATH: C:\Users\USER\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\USER\Desktop\HTML\react\learn-react\node_modules\.bin;C:\Program Files\nodejs;C:\Program Files (x86)\Yarn\bin;C:\Program Files\nodejs\;C:\Program Files\nodejs;C:\Program Files (x86)\Yarn\bin;C:\Program Files\nodejs\
9 verbose lifecycle learn-react@0.1.0~start: CWD: C:\Users\USER\Desktop\HTML\react\learn-react
10 silly lifecycle learn-react@0.1.0~start: Args: [ '/d /s /c', 'react-scripts start' ]
11 silly lifecycle learn-react@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle learn-react@0.1.0~start: Failed to exec start script
13 verbose stack Error: learn-react@0.1.0 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1028:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid learn-react@0.1.0
15 verbose cwd C:\Users\USER\Desktop\HTML\react\learn-react
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\USER\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v13.6.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error learn-react@0.1.0 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the learn-react@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

########   The Terminal cmd command Error

Error: No valid exports main found for 'C:\Users\USER\Desktop\HTML\react\learn-react\node_modules\postcss-safe-parser\node_modules\postcss'
←[90m    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)←[39m
←[90m    at applyExports (internal/modules/cjs/loader.js:502:14)←[39m
←[90m    at resolveExports (internal/modules/cjs/loader.js:551:12)←[39m
←[90m    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)←[39m
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:855:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1033:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (C:\Users\USER\Desktop\HTML\react\learn-react\node_modules\←[4mpostcss-safe-parser←[24m\lib\safe-parse.js:1:17)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1144:30)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! learn-react@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the learn-react@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Roaming\npm-cache\_logs\2020-11-01T18_25_06_686Z-debug.log

node -v : v13.6.0
npm -v : 6.14.8
Windows 7 Proffessional

**Comment by MBajaber** [comment]
why not answering me??????
